// ASCII bonsai from conifer.build (extracted from site bundle)
export const TREE_ROWS: string[] = [
"                                                                                             ,.                                                                 ",
"                                                                              ,. ., .:  : :..:= ,                                                               ",
"                                                                       .,.  ..;.. =;;=, i+zi.;,+,                                                               ",
"                                                                    ,;i;.;. ,,i,.;=is++:.;z;.iiiii,.;  ..   ,                                                   ",
"                                                                 ,=ii;,+=,=,;i=,X;==;s=x,i.;=zzxi==i,x =... =. i.....                                           ",
"                                                          ,;;;;;,;,=iXXii;W;isi=$zX+Xz==;iziixxx=+Xs+sX+i,,i+=:z;s;Xx:,.                                        ",
"                                                        .+XWiX;;W,=i,iW;;x=i;@zX@$W#W+@;=s==.s;=;=X+W$XWW#X@zsz+XzX=XsXX.                                       ",
"                                                    ,.,;;:X#WX#Xx;W=+iXWX#ziWW$@#$$W$#+#W@=Xi=i$W#@z;=#W@ziX#WXz@W##$#X;,                                       ",
"                                                     iXX=,;x$=Wz@zXXz@zzX$$z=sW$;$$$iiX$XWW#W+=i=@$WXx,iX@Xs;$XxXW$W@#=,                                        ",
"                                                  ,is=+z#XX#@z#@X#XWW#Wzx#$$$XX$W$$$sW#X$#$$$$$$$$$$$X:ix$Ws$$WXX#+#Ws.     ,.                                  ",
"                                                 ,=+;W@@Xz@#@$$$$zW$@@z$@+X$$+XWWx$X@X@s=i$$$$$@$$$$iW=,;#W$$$;Wz#$@;i,.iii,W.                                  ",
"                                               .is=+Xs#$$@z$$@@$$$$$@@$$$$$@x#$X$#$$$$=;#x$zW$$$$$@#W+W:=$i@$@$#Xx+XXzxsz=++$   ....                            ",
"                                             .Xz;+W=@@z$@$@#$$$$$$$$$$$$@$$$Xx@$W$$$$WX$@+=,$$zW@$z$$XXizWz$$X$WW#zX$@WzzxX#;i .ixX:i.                          ",
"                                           :=zW#z+ss+$X$$$$$z@$$$$$$$$$#@@$$+#zX+W$$Xz$WXW@$#xx$X@$W$$#X;=i@X#@@W$zX$@$XWi+#$;+=$#x=iii                         ",
"                                         .=;W@zX;#Xx@#$$$@$$$$@$z$$Wz$$X@@;Wi+isWizW$==$$$$@W+;..iz#$$$$$$WXW$$W;=WWz@zW$@$$X;z$@$$=, .                         ",
"                                          .,,+X@$@$$$$$$$$$$$$$Wxz@s+s;=#@=s=#@Xx+;ix$Wi=$$$@#WW@$z$$$$$$@WX@X$$$W@Xz$W@$$Wzs@@##+;,                            ",
"                                         .  iz;@W$$$$$$$$$$$$$z#;=z@Xs$i.;;+,,XXWs..;$$X=z$X=$X$;+$@ixX$=+.iWW$#$$$@$@=WzW$$$$Wi;,,+.                           ",
"                                       . : W+#X$z@$$$$$X#$X$$$WXx+;x#szX;z#=;=:;x,i:W#$#+$#i$$is$XXs+W$Wis,==i$$$$W@$#@W#$$@##W=W.,,,.. , .                     ",
"                                       .=;W$@$$$XWX$$$$W;$X@W$X$Xii:=@==X#$+;=.i=.iiX$@X;$=#$+z$W$$$$$X.   i,+XX$$isWX$@i$iXW;XXW.W:@. .,s .                    ",
"                                  ::,is,XX$$$@@$#i+$$$$@+$XX$@=@xXX+:iXzsiiWsXzi,,.;,=W+$@+@+X$X$@XzxWi+:i#=,zx@$$@ii$@#is,,+=x++Wz=,;XWXi=;,.                  ",
"                                 .i,==Wz.$$$$X@W$@;#$$@$z$@X$XXi;;@$X+i+zXiXzizi;.i.isXi$;X==W;W;=  i#@$$XXXi+i@zzz:=:i=;+ii;xX$Ws=WzXWs$$=+ii.                 ",
"                                 .i;:;X@#x$$$$$$$#@sz#$$$$$$iWWX;siXX@@z#$$#Xz,:##i,.,W.+X+,Xssi#Wzs  . ,.=s;+i=W# ;;Xi#;+ix=W$#Xs+#+@XW@Ws:xX=;..              ",
"                                 ,,.@X$$$Wz$$$$$@$Xx@=z@$$$$X#zXX#z$$$=sW#zWX,$$W$@x.+z,=zW+Ws.#$#,$z,   ,zWzW;+@;zWW=zWis;X=W$XXz$#z$;#XXX;@+X.;.              ",
"                                 .;,.:s#$$$$$$$$$XXis#X$$#$$WsX=i;:;+Wx...=W;$$$#i,++X$X##Wz;+;,+$#$$$$X+=WX+W$#x@$z::zW=s,s$$@@#=i#$=@@#XXXz;:+i,              ",
"                                 .,.  .,=x@$$$$@Wzz$@;;X@@=$zWX       $$X$$$;;zx,X$$@WW,W$zi;WXX,$$$$$$$;.XxW$$#@zXi=i,@;s =@$@zz+$W@$z#@#zWWzWi .=x,           ",
"                                :ix;,:XisiXixX#$$@@#$z=sxzsW$ii..ii.:X@XX@X@W@,;zs$$$=iW$X$X$$$$WX@WzsW$z. $$$=#+zX@$@+$$X=$$$@@$WW+XWX$$$$@W=i=$XxX=           ",
"                               iXi;z@#$W=+@W=i=#;#XW$@Xi;+ii;;X$$$$XX@$i,.. ,XziWx@@W,$$$s;:   . .i.., $$#XX$$W$$$$$$$W$$=X@@WW$$$$@@@$$$$$$z$$@zzz=i           ",
"                              iXXxXW$$$@x+zW=iiX#:+zi#@W#W$W$Wzsz#W#W=i, .i..#$$$$$$@$$$x:::;:;+,,,ixi.x$$$$$XzXXWx#$$@$$+WzXz$$$$$$$$$$$$@x+ii;;.,             ",
"                             ,W$;X=$$$$$zX@x@iX$zi.s;;,i=XXW;; =i;,,....,;;.=$$$$$$$$$$$$Xis,+=Xi+;;;;.,W;;x$$$W;=@+X$$Xz=..X$WX=+;+$$$XXi.                     ",
"                              =@$@XX$$$$#$WW@zW$W+W+;,,iWss$$;i,,iW@$W+:s$$$$$$$$#$$$$$$$$@z$ix#$$$$$XX+s:X++iX$$$$$$@##$#@$$Wx:iixWsi;..                       ",
"                              ;W;+$$$$$$$$@$$Xz$;xz......;W=Ws.W$$i#$$$$$$$$$$$X,  ;z$$$$$$#$X;$$$$@@W$i,X= i:.+=$$Wz$$$@#z$$$z$@#=i.                           ",
"                             .z@$@#$$$$$$$$$$Ws@z=...  ..i;;z$@#;+W$$$$$$$$$.i;i.i;:;$$$$$$$@$W$$$@@@@$$$$x.:i;sxXX;..,ixi.,.ii=i;;i;i.                         ",
"                       ..:;s=xWWXxX#$$$$$$$$$$X$;;= .;=#@i;+, ,i$$$$WW@z@$$,iW=.,W;z$$$$$$$XW$@#;  ..,X$$$W, .==W;,... ........,i:=.=#i,;iixWii.                ",
"                     ..ii,X@isWsWX#WsX$$$$$@=W@=@@##i=+;      :X$W,.,.,,,.; ,;+=@$$$$$$$$$$#$@W#,.,,;:=X,;X$Wxz.    .      ..  i.:,,+==+i;+zW=,=i.              ",
"                ii ;ii;:=+;$$$WX@W$x.Xz@$$$$;i==X;$$zXi==  .ii$$W.         ;i;W$$$$$$$$@$$$#$$$#X$$@$$,.=. z$$$z.       .   ,..,., #=i=;=:W#;=X,;,,;            ",
"          ,..;iiXx.zX$#@Ws#$@W$$+W$z@#x#W#$s$$=+W$x@$@WsW$$$$$$;,+Xsz=;,;;,.iX$$$$$$$$$$$$@W$$$$$Xx@$WXX@,  :+$#;;.;.,, ..  ....i.X+X==XX+sWix;==++,            ",
"          ,XX.z@z$;$X$z$WXX$@Wz$Xi$WXW$+XXi; .i;.. z$s.     i$@WWXz@$#;=$X$$$$$XzXW$$$$@z$$=.  ii+.i$WWx=i    .x@#$z@. +.; :.,;:X=zi;$;XzW=XX+zxi+;:i.;,;       ",
"         ..,=#@$$$$$W$$$##$$$##xW#$xx+$Xsz+i:.;. ..s$$+;;$$#is;s+z$=$$+$$sx$@$+=@==@$$$@$:+:;:+s.::i;xii#x=i:s,i@$$$W++=#XX:+;;;+=W#@$,s$Wi=XX=;$#=x=XXzii.  .  ",
"       iW;i;iX$$$$$$XWz$$$z$@+=WX+$WWz=#;i;=i:X, .;..iWW;WXXX+;iix=. :$$$#X@WsXz@W=$z;,... +.i,$$iz@zW;+;xX=ix;=$=z$X$z#z#Xi=i@s,+@XzW@WWW;W@XW=$z;#$XW+zi,:W+..",
"      .;+$Xz#WW$$$$$@WWXW$W#$#XXW#XWXzWWWzizss.;iXX@i#W+;i=:i;;xi+z@$$$X#$$$$#$X$s++..:..:=i.+x+#$xiX@W##;+;.i+=@x$#$$X$+Wz==X#W;W@$@$$#@XXXXz#$$$$WW@$W+X@#$sX+",
"     ;i;XX@$$#z$$$$$z@$$@$zW@#;=z$$@X+@@=$;XX;=$=$X$W$;+=i=W;$;=i==$@x@iW$$$$$;+@+i  .;+=;i=,:WzX+;iXXWx...;z=zzW,=X@$$W=X@XXxX@;$$$@XWWz$@$;x$$W$$$;XWxW#$$@ii:",
"      .+++zX$$$$@@@$$$$#@@$$$$$XXWz$$$W#i@+=XW=$$$X#$$WW#z;$+z+;++x@+is$$$$$$$#$X:  ..,i,+i+si+zs+WW$#@iii,;@x####$Xz$W#z#$$$W+$$=xXxX#$$$$$+W$$$$$$W$z#$$WWizii",
"       .,iiiX#$$$@$$$$$$XXW+;+@$z+X#$$$$;iW@WzWWWsX$@zX@;X;;;iiW;ii+X=XX$$$WW@$@z+i.i+Wi +Xi. i+$#;#z$=;  ,xXiX#$$$Wz$XsX#$$WX$$@z@$$@$$$@$#z$$$$$X@W@$$@@zX;=;i",
"         ix+xxxzX#$$$$$$##@$$$$@x+;Xz#$#@X$sxsX@$$z#@$#x.,,sXzX=:xxzW#=@x=+@$#W;;W$.   :xXX+,..+@##WW=i;z=+X;s#iW$#@#z@$$Xs#$$$$X$$W#@$$$$@$$$$$$$#$$$$$@WX++xW=",
"         .XWWWWWX;=+=i=W$#=+@iXW$$$$$@z#$$$i,#WX$$@@@Xi;@, Wz+XxXx$#=;.xX#$$$$$+=;@:   ;;, +X.  =$X;.sWX;x;#$$@x$Xz$=.,$$Wz$X$$+W#@$$$$$$#@$$@$$$@@$$$$@X==+i,,.",
"           ,,,,.,.    .;zX##$$zX#xWz=zW#$$$Wi=z@@$XW=+i..:;i$#WXizs=,::.W$$$$@$Wi;+=+=;;;..  ;.izz.,.::i:x$X,,i$$;;;. .,@$$$$$#s#Wz@W$$$$#$$$$$#$$$Wz;,         ",
"                          ..,.  ,=@$$Xzi..,X;;XWW$z$W@z@i,z$;=,+;i=ii;,.,W$$$$=zWX$$WX;+;.=X. .=     s;s.izX=, iz;         ,z$$X;:.sz$$@@XzW@$$Wz;=.            ",
"                                          ,W$#s+:     +zX;..            .:$$$$sX=s$XXsi,W=.,ii,,...:;=+ii.;,                  .+s#$$=z@W;=X=..  .               ",
"                                                     .                .... @$@$$z$$W@+=;W$z,,;,+X$$$$$X@@+X+zi                                                  ",
"                                ... . .          . ,:               .:;:iiW$$$$$$$#=XXz++W@@$xixW@$@#X@W$$$#Wi+.                                                ",
"                               ;i,  , ;. ; .  ..i, ;   .       . . ;W$$$$$$$$$$$$$$x.    s;=X$z=z+     @$$$$@#X,i;.                                             ",
"                             ,=z;,..; i;+;   i;:Xs;i, .   ,  . .;i@W@$$$$$@$Wsi=$z=@$=;.    ,,;,     .=$@.,i@@Wx+W$s==@i..           .                          ",
"                           :i,;;X;i,W.;i ,=; +,.;zz;=      ,i, .X$@$zW$z;+;,i;.=..X=$$$$W.          .+@@$W,  +$zW#W$z#=$=.,          ; :  ,, si..               ",
"              .  .    ....;,;i=;i=.:.,XXis;:ixXW@$X:,..+;;;,;+ =$$$@$=.:,;i;#i++.=;,+;;i$@+        ;X$@#i,i   ,=XX+:iW$$z.=,        ;i.: :.,i+ii..W.;., ..      ",
"         ,,. :; .; ,, ..;+X=.x;Xz+z+XX$sW#W iiiXiW$+;x=;;XWW$@$$$$$#z;=iX. ;z$X;;iX+=. ..;X      .==X@WXz,..          XW..z:   . : .W;=;i+=xWiX;;iW=ii.x;,,     ",
"       . .s;;,izx;#+i:+W#$is.s#WW@W@@$$;.zzii;+,+W$=;#X$$$$$$@$$$$$XWXW=+i;;iWsx=zi,:,,          :ssisX=szi.i,      .Wi. iX;  ..,;+:;==i@sX=WiizWX@Xsi+;iiz:    ",
"    .ii.,+,XzWX#zxz;Wi=@$#.$z#z@W$$$$X$@ x=.z$=. ..z;$$$$$$$z#$W$Wz#;#$i ,Xs;@$X=i,;,.            .X$=X#;X$=.;,    .$X.. z$$i,,.,;X;;iW=X=;#X=Xi;#$#;X;iW=;+,   ",
"  :ix+iXxz+X$W#$$#@i$==s$$W$#@#$@iWW=@$$$#+W+.,,,=W$$$$$$$$z@$$$xXXzi##:i:,,i@X:.                  .iXssWz$$,,$i   :$WX;,+#@WXX$$X+xiiXss#$$XX@#$$@$$@$=,++;i;i ",
" .,;;WX$$$$$$$@$@$$Wz=z#@x=$$W@==X. @$$$z@,.X$$$@WW,iz$$$$XX$$$=$$WWW$@i=XWi .                      ,$;z$@z$@xXW;iW$$$Xx=i, ;WzWiX@WXs$Xz;z@$@$$$zX+$X;;i=$+XWi.",
" .i====#$$$#$$W$$#$$$$$W#$$$$@z#X+ii$iX;,,+W@;.:;W$$$$$$$@W+i;. ;=z#=i .                          .=$$$@#$X$$Xi$$##$$WX$+i,=i;+xXzX@z+x+iX$$$$$$$#XzW+zW$$WXz;..",
" .,:WXW@z$$#$W$$@WzX$$$$@$$$W$$+=i=s.  . :z$$$$$$$z@$$W$@@zW     .=+ixi                       .;XW$$$$;$;+$s$$i$@;.. . @W@XWi.=$$$@W$@W=z$$$$$$$$WW;XiW$$$X=,,Xx",
" ..;xx++WWX$$$$$$$=$$WXX@s#$@W$$WWWiz;xW@@z,.ii.,i=#$$@$WWs.                                ;@$$$$$@$$XsiX$=X=X;.. , i :W$$WWX@z$zWWz$$#$xWiiiWz#zx=+siXz;i;;x,.",
" ii;W#zW$$X;$W$@$$WXXWzX;Wz+z#$WXi,i$#@,,.;Xz@$$@XW@$$z$i,                                 ,@$$WW$$$W@$@zXWX;XX;,;;.,:,;=X$$X$$+;+;WW$$$$#@sXi$+WXzz;;,z;iziXiX,",
":#W:=s;z#XX$$W$$WW$XX+i+is@W$W@WXXsXiiizW@$$$W$$zW==Xs,=  .          .;;i===XX#zs;         ,$$$#@zx$$##$zx+WWzXzs=x;i+i==+xWW$@WXX#@$$$$$$+=$+$WxW$$#X#Xzsx=Xz=+",
"=@XX$$$zzXXW@#;W@X$@;:X#z#XWWxX;,s@@W$$+X#$$W$WzW,;:,+ ii:. ;      ,W$XWWXi,@@Wzzx         .$$zzW+XWWWWW$@X#$zzW@x;Xz+;x;=XWW$$XzX@$XW$$$+;x$+@X$X@$zxWi.$X$z;;W",
"x$@W$X$$$@XsX@@#=+Wzz@$s$#$W#WWW=#$$$sXx$@$$W#@xiii,:,i++..: .,. ,#$#XWx@$$$$$$@s,..       .@$$@#@ssXz$@=#$$$@$#x:+@@X=zX#X+$$zWX$$W$+i=@+is=@$W#$@W#WXXisXX#sXs",
"z$z$$#$$$@XW$W;#zi;X@@$#zX$z@X$W$#z+@+;;=i i$X,@Wi,sX,=i :,.=i; i$$XXX$X$$zWz=XWz$$X;;=;    =#$z@@@@@#;#$X@$$$@;,s@W$@XzW;zW,@$$iW@#X$X;,,.iz#=..i$XzWzz$Xix$Xzz",
"+$$$$$W$$#$$W#XWiXXxX@=$X@#$$W#XXWW=XxXzXz;@XiWs:s#W;i;,,+iz,. i$W+i#$$$$;Wsxi+;@@=iis+X;   W$$WXX$@WX+ix$$$$$i+.=.:X$@##W$$=$$$$$$@@#,:.i=s$@$#,iW#@$$zXxXX@Wzz",
"X@$@$$@$$@@$XWzzXX$$WW@@$$@$$X@XX+;#W;$+W$$@z$X.XXiXW=iX=W= .iWX;W;X$$W#=+WXXXX#@W@#WX$$i   ,W@W@$@s,+==;X;X$$z.;:,@$sX$W$$$@$$$$$$$$$X#@$$$$$$$$WzW$$$@$@@$$W@X",
"X$$$@W$#$$@$#$@z@+xX=sz$$XW$$@$W$$$#+W$##$$$$x..;zW$@$Xxxii:+XW$$@W@$@$W==z$+z+=X$$$$$i       ,,:.          .;+Wx$x=;.;=i=z$$X=$x+.ixzW$$$W+X$$WX$$W$$$$#X##$$X.",
"X$$$$$WW$$@zWi=XW+WW;+zi$#X$$$$$@XW$@+X@@@;W;; $$+z$@W;;,;iXW=z$@$WX@@$@WXz$;X@WW$@#$$z,                               :;+;X$+.         =@$$$z$$$$@$$#i,,;WXWi  ",
"iW$$$$$$$$$$$@x@x$+W$sxz$$$$$$##zX@#XXiW#X+@$$@$$#X:....+z@WX$X@@$$#X$$$Xi;xiX$W;Wz+W#z,                                                  .::;==,,;si,:;;;,.    ",
";$$#zW@$$$zz$@;+X@@W@$$$$X$$$XX$$W@x,+iXz$X$$Wzx,     ,iXW$$$$@+=@$$W$$#$WXs=X$i=X@@$$X.                                                                        ",
",s++isXW$#sW@z+X;z$$@ziii;i+=Wz$$$$@$$$W$#+#WXWsxxi. iiWW@@$$$$$;:X$$W$@=W$=;W$zxX$$$i                                                                          ",
".i=i;i=;,:=#$zz@@z@z..       .ixzz$$$=i+=i=..     ,,;#$#X$$$Xz,$XiX$$X ;i#=@;i$$@z$s                                                                            ",
".....       .::i;;.                        .      :$$$$$$$$z,+XWX$$@$:i+:$$$W$$$$$$,                                                                            ",
"                                                 .@$W$@$$$Xx;$$XXszi@Wz,i$W@z$$@$z$                                                                             ",
"                                                .#xX$X=:@#+W$$=z.,XW$siX@W$$$$$.,$z                                                                             ",
"                                               .z$W@$.;@@Wz$@$.;W$zs ..$X=ii.:;  ,.                                                                             ",
"                                               x$$.@.:$,,:+W#z :=s:i+$=:  :.==                                                                                  ",
"                                               $@=X$= @  ;=$@ ...+,i.  .                                                                                        ",
"                                              :$$ix#,;i;;,.#XX#..     ,..,i.:                                                                                   ",
"                                             .$$i#W$ ; +,+X+$#=#,i,.Xi.i;:X;.i . ,X:                                                                            ",
"                                             .$X$#;# $,+$#++$s;z i;W;:=;iiii==i+;X., .,                                                                         ",
"                                              =#ii;+ s$zzWXiis XW$$ Xi.. i=x ;=X=i=. $W                                                                         ",
"                                              $$;;X$  #$$$X=iizi,W$:=.+,.;=XX. ...  ;,,:;:i.                                                                    ",
"                                              $x=Wz$= X$$z,$;,@X@x$X$#,,;=. .x ...z=$ii+@sWX                                                                    ",
"                                             .#z;=;zWs,@$z XW+;@$Ws+=W$@$$$#@s+W=#i+:ii==@@$i                                                                   ",
"                                              ;$ + :.,,xi=..,X$iWi;$$+XX$$X$@$$$$$zzz:.. ,;@z.                                                                  ",
"                                             ,#W.@WX$#$W$+$z =$s+=x+=W$@W+@z,i#$$W$$x#X=#$+;;                                                                   ",
"                                            ;@@iXWi $+z$X+=$@x=.i=z$$$W=z+i.z$Xi@xz$WWzW=                                                                       ",
"                                           :$@.i;s.##sX$$xXs.=#s,:;W++W+;;+;;zs=i@s                                                                             ",
"                                          iX;izWXW=$WXWi $X.$#iz,+@X;.;$$@.. iWX,iW;                                                                            ",
"                                         =WW;+.#sisW$W$=s$@i#WWW$Xz:=s.,X$i,:,WXz@#,                                                                            ",
"                                         $z$i. si$@;    ,;X.iX=$WWWx,;=xi X$; .;,W.                                     ,i=i,                                   ",
"                                        ,=,s+@W+;W.         :,si,=#$;X$XzWi;s+=XW=:.                                  ;+===X$$$X+;;.                            ",
"                                     :=i,.;xWx@i,.  ,ii+.      ;;x.i, @$$X,x;z,iW$$i.                                ,Xi,;ii..$$$X=zX                           ",
"                               :;i+$W$+ix+=W,#i:+##+XW ;;:        ,,...,+;ii;XWsX+=,                                 .,Xx$$ixzi=X$$@$+.                         ",
"                           ,=WW+$X,;==X=;+=W,$W$$;,.. .@$+;=.                .= ,i,                                    .iXX;i;$iXX;#$$@,      ..                ",
"               .,.....  .+$$$@XX=iii+xixWWWss#W$+  ...:$Wi@zWXW,;                                                         iz#x.;++=++W#$$$$XX;i,.               ",
"           .,;,. ..  .,z$$$$WW@x=+z+i.;$$$$WX;X#,  .Xx,x$$$=.#$$Xz=,..                                                      X$zXW;. ,. ;W@$$$@;s$.              ",
"          .,:...iii=+@zWW$#XWW=s.##Xzi==iz$@$z+;z@zW#$i;#W i;+XXX=i@$i,i;:i.,:szz+;:;:,                    .....     .,.,,.iz$$$$;i@=;;ss=#@@@@$$$=$=i.         ",
"        ,,i. ,W$$X$$X;z$$$$@$xi+;i;xWXWXX+$$Wi@$zx,i.z@X=$@@$@$$;W$$.$@XX.$@$+Wz;+XX$.;;i+X$ii;=XX;;=;i+X=XXi.z$$#WiX$$#$. $$$X#$ @$$#$X=;=+W;X$$$i@;#W$W,      ",
"        , .:$s#W+$$zW$$@XXW$@sWXWXW$W$$#@$z$$####$@zX=#$X#$X.::.++@=+$s:x#$$+Wii,X+xXs#x$+,WXz;s#X;ix;ii#:..   i#zz: .,s i  i@XWWs.$@$$$$sz=Ws+X;;x:,;.;z$=,    ",
"       .  X=Xi;+XW;$$iX;@$$$WX$$W$W@W$@$$$z$$,iz.X@$$,$$$,.,. .,W:X+@W==,=.;ixXi@.zX  ;=;#.+W=;. ,i; s.,X:,+=.,,.;.izzX,  i$$X=.iX$$W+$$zWW$W$$W=xzzXizxiWW$i.  ",
"         ,x:ii,=xiWX$$$$$$##$$$$$$$@$$$$$@@$#@$$#s@$z$WXW+....i+iixsX+;;==i;,..;+si+x,  +:=:;i+==s=@$sz+XzW=s;z#$$$$$sizx==#$#xWW+.;+=x@$$$$$XW$$@WX$$#+XsX$+.  ",
"       ., i,;==i=s,#$$$$$$$$@W$$$$$$$$W$$$$$z$X+z+X=@=i. i.i,+WX@X;#W+i..W  ;; ,ziW+=+;..,;+;=z$$@zXX+z+;W=i;z=s@WX+@$WzX;,.,. +z,... .,$$$$$$z$$$$$$$$$z==+..  ",
"         .. .;;+i;,i@xXX;##WX$$$$$#$$WX@s#$$#W==xzii .xz+ii:ii.,: ;i.s;;.;: ,.i..=WsWi+zx###$$+@@$$#@$$#XsXsiX#ss=+sX@+=WXXXxzi;zX$$z..#=$XWW$$W;i:X$WXxXi.     ",
"            .  ,zi;= :..Wz, i, :$X +@=i$i  .. ,;i;.  . ;.i;;.#$#X, x  W; =   ,=+ii .$$z+$$;X$$zW@$$W$X;$$X=W@@z$$XW+W;W$XW;W$WXz,. =$Wis;xX;=@.:@i,,i=,   .    i",
"              ....:::. ;W;.:i,.,;+s+.,W; :iX .i; . ..  :;i,,=sX,;:., : ;;i+ .=,i+s+i@$$@$$$$X$$$z$$@$$$$$$$W+$X@$$@X$$$@$#$X$@X#W+i.,=W;i;;;i,.+;:.     ..,:ixsx",
"                         . ,=,. . iX..   W=z=+$;., .;...,  +i. .i  .,:;z ,.,. .  .Xii=W+$#X@W$$$$$$$zWW$@$W$$$W$W$$@W#$W@WWWW+$;@..i,;z.=,.        .,;,i==$$@X@i",
"                       ...:::.... .....,..:z++:  .,;:+$+::.., .. ,, .:,x;;:. . .i. ..:z,.ix:+:s+$$z#X#$$$$$$$$W+XW$$i;$i@#X,... ;         ,.. ...;i:,;$$@WW$zW=,",
"                                .;i;,,,...,,,i=,,,.+...;....  .  :    .,=.i iX    X+.,  .    i. i:   iW  W;X= i  ,i:.            .,,,;.   .;;Xz$Wi;Wzzzii;=x=sz,",
"                                     .,,;::,,,..,iii;;;;;i;i;i+i=;s:iis,;i=,,;,,;...;.  .  ...  . ..,,:..                ..........:iiWs=i=s##@Xi;;.            ",
"                                                        ..,......,,,..,..  .  ..                                .. . ,.:i+,;X==;;;XXXxi,..                      ",
"                                                                                                                 .,,...;;;;;....                                "
];
